version: '3.7'

services:
  pg_db:
    container_name: pg_db
    image: postgres:10.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    restart: always
    build: .
    command: python /usr/src/cpu_loading/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/cpu_loading
    ports:
      - 8000:8000
    depends_on:
      - pg_db

  redis:
    image: redis
    restart: always
    container_name: 'app_redis'
    command: redis-server
    ports:
      - 6379:6379

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

  # рабочая настройка
  celery:  # для корректного отображения созданных файлов (скаченных файлов)
    restart: always
    build: .
    container_name: 'app_celery'
    command: celery -A cpu_loading worker -l info
    volumes:
      - ./cpu_ldng:/usr/src/cpu_loading/cpu_ldng
      #-  ./cpu_ldng:/usr/src/cpu_loading --- ./cpu_ldng - локальная папка внутри cpu_loading
    links:
      - redis
    depends_on:
      - web
      - redis

volumes:
  postgres_data:
