# Generated by Django 4.0.5 on 2022-06-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_ldng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstartstop',
            name='Start_Model',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='modelstartstop',
            name='Stop_Model',
            field=models.CharField(max_length=30),
        ),
    ]
