# Generated by Django 4.0.5 on 2022-06-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_ldng', '0002_alter_modelstartstop_start_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelstartstop',
            name='Stop_Model',
        ),
    ]
