# Generated by Django 4.0.5 on 2022-06-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_ldng', '0003_remove_modelstartstop_stop_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstartstop',
            name='Stop_Model',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelstartstop',
            name='Start_Model',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
