# Generated by Django 4.0.5 on 2022-06-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpu_ldng', '0005_alter_modelstartstop_start_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstartstop',
            name='Start_Model',
            field=models.CharField(blank=True, default='novalue', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelstartstop',
            name='Stop_Model',
            field=models.CharField(blank=True, default='novalue', max_length=30),
        ),
    ]
